---
openapi: 3.0.2
info:
  title: Leaderboard API
  description: Leaderboard service for seeing who the top scorers are in a game
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
    description: Main local server
paths:
  /leaderboard:
    get:
      summary: Returns the top scorers across every game and no specification on timeframe.
      responses:
        '500':    # status code
          description: An error occurred during processing.
        '200':    # status code
          description: A JSON array of Leaderboard objects
          content:
            application/json:
              schema:
                type: object
                properties:
                  player:
                    type: string
                    description: The players username.
                  score:
                    type: integer
                    description: The players score.
                  game:
                    type: string
                    description: The game which the score was earned for.
  /leaderboard/{gameId}:
    get:
      summary: Returns top scorers for a particular game and no specification on timeframe.
      responses:
        '500':    # status code
          description: An error occurred during processing.
        '200':    # status code
          description: A JSON array of leaderboard objects
          content:
            application/json:
              schema:
                type: object
                properties:
                  player:
                    type: string
                    description: The players username.
                  score:
                    type: integer
                    description: The players score.
                  game:
                    type: string
                    description: The game which the score was earned for.
  /leaderboard/{gameId}/{dateRange}:
    get:
      summary: Returns top scorers for a particular game between a date range.
      responses:
        '500':    # status code
          description: An error occurred during processing.
        '200':    # status code
          description: A JSON array of Leaderboard objects
          content:
            application/json:
              schema:
                type: object
                properties:
                  player:
                    type: string
                    description: The players username.
                  score:
                    type: integer
                    description: The players score.
                  game:
                    type: string
                    description: The game which the score was earned for.
  /achievements:
    post:
      summary: Accepts an achievement in the form of a JSON object, and saves it to the database.
      responses:
        '500':    # status code
          description: An error occurred during processing.
        '201':    # status code
          description: Achievements were created
  /achievements/{achievementId}:
    get:
      summary: Returns a breakdown of an achievement and highlights various data points around it.
      description: Breakdown that highlights data points about achievements from a few different categories; frequency, first occurrence, last occurrence, number of times earned by players.
      responses:
        '500':    # status code
          description: An error occurred during processing.
        '200':    # status code
          description: A JSON array of achievements and supporting data
          content:
            application/json:
              schema:
                type: object
                properties:
                  achievement-code:
                    type: string
                    description: The code for the achievement.
                  frequency:
                    type: integer
                    description: The number of times the achievement occurred.
                  first-occurrence:
                    type: string
                    format: date-time
                    description: The fitst date when the achievement occurred.
                  last-occurrence:
                    type: string
                    format: date-time
                    description: The last date when the achievement occurred.
  /achievements/{achievementId}/{date}:
    get:
      summary: Returns the number of times a particular achievement has been earned on a specific day.
      responses:
        '500':    # status code
          description: An error occurred during processing.
        '200':    # status code
          description: Number of times an achievement was earned.
          content:
            application/json:
              schema: 
                type: integer
  /achievements/{gameId}/{dateRange}:
    get:
      summary: Returns a list of the different achievements earned by players in a game over a specific date range.
      responses:
        '500':    # status code
          description: An error occurred during processing.
        '200':    # status code
          description: A JSON array of achievements
          content:
            application/json:
              schema:
                type: object
                properties:
                  achievements:
                    type: object
                    properties:
                      achievement-dt:
                        type: string
                        format: date-time
                        description: Date/Time the achievement was earned.
                      player:
                        type: string
                        description: The players username.
                      game:
                        type: string
                        description: The game which the achievement was earned for.
                      achievement-code:
                        type: string
                        description: The code for the achievement.
  /players:
    post:
      summary: Accepts a list of player information and stores it into the database.
      description: Processes the player data sent in the form of JSON or CSV, and tries to store it in the database. In the event of an error, a list of objects will be returned for ones that couldn't be processed.
      responses:
        '500':    # status code
          description: An error occurred during processing.
        '201':    # status code
          description: Players were successfully added.
  /players/{username}:
    get:
      summary: Returns a chronological list of every achievement ever earned by a player.
      description: Returns evrey achievement ever earned by a player in the order they achieved them. Also accepts an optional query parameter of a gameId to filter the results.
      parameters:
        - name: gameId
          in: query
          required: false
          description: Optional parameter to further filter on a secific game
          schema:
            type : string
      responses:
        '500':    # status code
          description: An error occurred during processing.
        '200':    # status code
          description: A JSON array of achievements.
          content:
            application/json:
              schema:
                type: object
                properties:
                  achievements:
                    type: object
                    properties:
                      achievement-dt:
                        type: string
                        format: date-time
                        description: Date/Time the achievement was earned.
                      player:
                        type: string
                        description: The players username.
                      game:
                        type: string
                        description: The game which the achievement was earned for.
                      achievement-code:
                        type: string
                        description: The code for the achievement.
  /players/{username}/{achievementId}:
    get:
      summary: Returns a date that the player earned a particular achievement.
      responses:
        '500':    # status code
          description: An error occurred during processing.
        '200':    # status code
          description: A string representing a date
          content:
            application/json:
              schema: 
                type: string
                format: date
